### ISSUE TITLE
java.io.IOException: Not a data file

### ISSUE THREAD

**Issue by youngki924** [gilt/logback-flume-appender#13]
Event is sent to flume agent and works well if sink is logger.
2017-01-25 11:40:02,361 (SinkRunner-PollingRunner-DefaultSinkProcessor) [INFO - org.apache.flume.sink.LoggerSink.process(LoggerSink.java:94)] Event: { headers:{application=myApp, level=DEBUG, logger=com.datastax.driver.core.Connection, host=localhost.localdomain, thread=cluster1-nio-worker-3, type=DEBUG, message={} heartbeat query succeeded, timestamp=1485362400028} body: 43 6F 6E 6E 65 63 74 69 6F 6E 5B 6C 6F 63 61 6C Connection[local }

But when I switched sink to MorphlineSolrSink and get exception for readAvroContainer.
(readLine works but has a problem with multi lines)

[flume.conf]
a1.sinks.k1.type = org.apache.flume.sink.solr.morphline.MorphlineSolrSink
a1.sinks.k1.morphlineFile = conf/morphline.conf

[morphline.conf]
      {
        readAvroContainer  {
        }
      }

[exception]
2017-01-25 15:33:23,097 (SinkRunner-PollingRunner-DefaultSinkProcessor) [ERROR - org.apache.flume.sink.solr.morphline.MorphlineSink.process(MorphlineSink.java:163)] Morphline Sink k1: Unable to process event from channel c1. Exception follows.
org.kitesdk.morphline.api.MorphlineRuntimeException: org.kitesdk.morphline.api.MorphlineRuntimeException: java.io.IOException: Not a data file.
        at org.kitesdk.morphline.base.FaultTolerance.handleException(FaultTolerance.java:73)
        at org.apache.flume.sink.solr.morphline.MorphlineHandlerImpl.process(MorphlineHandlerImpl.java:134)
        at org.apache.flume.sink.solr.morphline.MorphlineSink.process(MorphlineSink.java:141)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.kitesdk.morphline.api.MorphlineRuntimeException: java.io.IOException: Not a data file.
        at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:98)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
        at org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:181)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
        at org.apache.flume.sink.solr.morphline.MorphlineHandlerImpl.process(MorphlineHandlerImpl.java:128)
        ... 4 more
Caused by: java.io.IOException: Not a data file.
        at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:105)
        at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:97)
        at org.kitesdk.morphline.avro.ReadAvroContainerBuilder$ReadAvroContainer.doProcess(ReadAvroContainerBuilder.java:121)
        at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:96)
        ... 8 more
2017-01-25 15:33:23,109 (SinkRunner-PollingRunner-DefaultSinkProcessor) [ERROR - org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:160)] Unable to deliver event. Exception follows.
org.apache.flume.EventDeliveryException: Failed to send events
        at org.apache.flume.sink.solr.morphline.MorphlineSink.process(MorphlineSink.java:186)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.kitesdk.morphline.api.MorphlineRuntimeException: org.kitesdk.morphline.api.MorphlineRuntimeException: java.io.IOException: Not a data file.
        at org.kitesdk.morphline.base.FaultTolerance.handleException(FaultTolerance.java:73)
        at org.apache.flume.sink.solr.morphline.MorphlineHandlerImpl.process(MorphlineHandlerImpl.java:134)
        at org.apache.flume.sink.solr.morphline.MorphlineSink.process(MorphlineSink.java:141)
        ... 3 more
Caused by: org.kitesdk.morphline.api.MorphlineRuntimeException: java.io.IOException: Not a data file.
        at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:98)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
        at org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:181)
        at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
        at org.apache.flume.sink.solr.morphline.MorphlineHandlerImpl.process(MorphlineHandlerImpl.java:128)
        ... 4 more
Caused by: java.io.IOException: Not a data file.
        at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:105)
        at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:97)
        at org.kitesdk.morphline.avro.ReadAvroContainerBuilder$ReadAvroContainer.doProcess(ReadAvroContainerBuilder.java:121)
        at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:96)
        ... 8 more

**Comment by javierarrieta** [comment]
I understand that this is happening when using the sink, not when using the appender. 

By the looks of it it tries to read a file, I guess trying to get the schema from the file (inputstream) header
